repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.15.0
    hooks:
      - id: golangci-lint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: no-commit-to-branch

  - repo: https://github.com/danielhoherd/pre-commit-circleci
    rev: v0.0.3
    hooks:
      - id: circleci-validate
